name: Build

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: ls -lah && pwd
      - run: make all
      - name: archive
        uses: actions/upload-artifact@v2
        with: {name: pngpaste, path: pngpaste}
